# Generated by Django 2.1.7 on 2019-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=18)),
                ('birthday', models.DateTimeField()),
                ('addr', models.CharField(max_length=200)),
            ],
        ),
    ]
