# Generated by Django 2.1.7 on 2019-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_age', models.IntegerField(default=18)),
                ('user_birthday', models.DateTimeField()),
                ('user_addr', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
